apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
      imagePullSecrets:
        - name: regcred