apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: postgres-storage-{{ .Values.namespace }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G