name: "Deployment"

on:
  push:
    branches:
      - charts-sources

jobs:
  compress-chart:
    runs-on: ubuntu-latest
    if:  github.event_name == 'push' || github.event.pull_request.base.ref == 'charts-sources'
    env:
      BASE_WORKING_DIR: ./
    defaults:
      run:
        working-directory: ${{ env.BASE_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v2
      - name: Terraform plan
        run: |
          array=($(ls | grep bb-))
          for i in "${array[@]}"
          do
            echo "$i"
            cd $i
            ls
            array2=$(ls)
            for a in "${array2[@]}"
            do
              zip -qq -r "${i}-${a}.tgz" $a/*
              cp "${i}-${a}.tgz" ../
              cd ..            
              git config --global user.email "bitbark.os@gmail.com"
              git config --global user.name "Bitbark Bot"
              git fetch
              git checkout charts
              git add "${i}-${a}.tgz"
              git commit -m "Update chart with ${i}-${a}.tgz"
              git push
            done
            cd ..
            # or do whatever with individual element of the array
          done
