name: "Deployment"

on:
  push:
    branches:
      - charts-sources

jobs:
  compress-chart:
    runs-on: ubuntu-latest
    if:  github.event_name == 'push' || github.event.pull_request.base.ref == 'charts-sources'
    env:
      BASE_WORKING_DIR: ./
    defaults:
      run:
        working-directory: ${{ env.BASE_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v2
      - name: Terraform plan
        run: |
          array=($(ls | grep bb-))
          for i in "${array[@]}"
          do
            echo "$i"
            cd $i
            array2=$(ls)
            for i in "${array2[@]}"
            do
                zip -qq -r "${i}.zip" $i
            done
            cd ..
            # or do whatever with individual element of the array
          done

  push-chart-gz:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      BASE_WORKING_DIR: ./src/environments/dev
    steps:
      - uses: actions/checkout@v2
