name: "Deployment"

on:
  push:
    branches:
      - charts-sources

jobs:
  compress-chart:
    runs-on: ubuntu-latest
    if:  github.event_name == 'push' || github.event.pull_request.base.ref == 'charts-sources'
    env:
      BASE_WORKING_DIR: ./
    defaults:
      run:
        working-directory: ${{ env.BASE_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Compress and upload to artifact
        run: |
          array=($(ls | grep bb-))
          for i in "${array[@]}"
          do
            cd $i
            array2=("0.0.1" "0.0.2")
            for a in "${array2[@]}"
            do
              helm package $a --version $a
              echo "$a"
            done
            mv *.tgz ..
            cd ..
          done
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: "*.tgz"
  push-chart:
    needs: compress-chart
    runs-on: ubuntu-latest
    if:  github.event_name == 'push' || github.event.pull_request.base.ref == 'charts-sources'
    env:
      BASE_WORKING_DIR: ./
    defaults:
      run:
        working-directory: ${{ env.BASE_WORKING_DIR }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Copy tgz to a temp directory
        run: |
          cp artifacts/* ../
      - uses: actions/checkout@v2
      - name: Git push
        run: |
           git config --global user.email "bitbark.os@gmail.com"
           git config --global user.name "Bitbark Bot"
           git fetch
           git checkout charts
           cp ../*.tgz .
           git add *.tgz
           git commit -m "Update chart with tgz"
           git push
  update-index:
    needs: push-chart
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.base.ref == 'charts-sources'
    env:
      BASE_WORKING_DIR: ./
    defaults:
      run:
        working-directory: ${{ env.BASE_WORKING_DIR }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Update Index
        run: |
          git config --global user.email "bitbark.os@gmail.com"
          git config --global user.name "Bitbark Bot"
          git fetch
          git checkout charts
          helm repo index .
          git add index.yaml
          git commit -m "Update chart index"
          git push
